
export const TOKEN_SYMBOL = {
  PUPPET: 'PUPPET',
  GMX: 'GMX',
  GLP: "GLP",
  ETH: 'ETH',
  WETH: 'WETH',
  UNI: "UNI",
  LINK: "LINK",
  AVAX: "AVAX",
  WAVAX: "WAVAX",
  ARB: "ARB",
  SOL: "SOL",
  SynDOGE: "SynDOGE",
  SynBTC: "SynBTC",
  SynLTC: "SynLTC",
  SynXRP: "SynXRP",
  NEAR: "NEAR",
  OP: "OP",
  AAVE: "AAVE",
  BNB: "BNB",
  PEPE: "PEPE",
  ADA: "ADA",
  TRX: "TRON",
  MATIC: "MATIC",
  WIF: "WIF",
  ORDI: "ORDI",
  STX: "STX",
  SHIB: "SHIB",
  ATOM: "ATOM",
  DOT: "DOT",

  USDT: "USDT",
  DAI: "DAI",
  USDe: "USDe",
  USDC: 'USDC',
  FRAX: 'FRAX',
  MIM: "MIM",
  WBTC: "WBTC",
  BTCB: "BTCB",
  BTC: "BTC",
  USDCE: "USDCE",
  WBTCE: "WBTCE",
  ESGMX: "ESGMX",
} as const
