name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  checkout:
    name: Checkout with Submodules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    needs: checkout
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_WEBSITE_SERVICE_ID }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}

  deploy-indexer:
    name: Deploy Indexer
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    needs: checkout
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_INDEXER_SERVICE_ID }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}