name: Deploy Indexer to Railway

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

# Ensure this doesn't run on PRs from forks
permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          submodules: recursive

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Build all packages
        run: bun run build:packages
