name: Deploy to Railway

on:
  push:
    branches: [main]

jobs:
  checkout:
    name: Checkout with Submodules
    runs-on: ubuntu-latest
    outputs:
      indexer-changed: ${{ steps.changes.outputs.indexer }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 2
      
      - name: Check for changes
        id: changes
        run: |
          # Check if indexer submodule changed
          if git diff --name-only HEAD~1 HEAD | grep -q "^indexer$"; then
            echo "indexer=true" >> $GITHUB_OUTPUT
          else
            echo "indexer=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: .

  deploy-website:
    name: Deploy Website
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    needs: checkout
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_WEBSITE_SERVICE_ID }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}

  deploy-indexer:
    name: Deploy Indexer
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    needs: checkout
    if: needs.checkout.outputs.indexer-changed == 'true'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_INDEXER_SERVICE_ID }}
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace
          path: .
      - name: Deploy to Railway
        run: railway up --service=${{ env.SVC_ID }}